services:
  mongodb:
    image: mongo:6.0
    container_name: apostrophe-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    command: ["--bind_ip_all"] # Ensures MongoDB is accessible in WSL

volumes:
  mongodb_data:
    name: mongodb_data  # Forces consistent naming to prevent namespace issues
